#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar position=top height=22 blur_radius=0 color=0xff2e3440 \
  y_offset=7 margin=10 padding_left=0 padding_right=0
sketchybar --bar display=all
sketchybar --add event aerospace_workspace_change

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="Monocraft Nerd Font:Bold:17.0"
  label.font="Monocraft Nerd Font:Bold:14.0"
  icon.color=0xffD8DEE9
  label.color=0xffD8DEE9
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Workspace Block #####
sketchybar --add item aerospace left \
  --subscribe aerospace aerospace_workspace_change \
  --set aerospace \
  background.color=0xff5E81AC \
  background.corner_radius=0 \
  background.height=22 \
  background.padding_left=0 \
  background.padding_right=8 \
  background.drawing=on \
  icon= \
  icon.color=0xffECEFF4 \
  icon.padding_right=6 \
  label.color=0xffECEFF4 \
  label.padding_right=12 \
  label.font="Monocraft Nerd Font:Bold:14.0" \
  update_freq=2 \
  script="$PLUGIN_DIR/aerospace.sh"

##### Current App Block #####
sketchybar --add item front_app left \
  --set front_app \
  background.color=0xff5E81AC \
  background.corner_radius=0 \
  background.height=22 \
  background.padding_left=8 \
  background.padding_right=8 \
  background.drawing=on \
  icon=">" \
  icon.color=0xffECEFF4 \
  icon.padding_left=8 \
  icon.padding_right=8 \
  label.color=0xffECEFF4 \
  label.padding_left=4 \
  label.padding_right=12 \
  script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

##### Now Playing Block #####
sketchybar --add item now_playing center \
  --set now_playing \
  background.color=0xff5E81AC \
  background.corner_radius=0 \
  background.height=22 \
  background.padding_left=8 \
  background.padding_right=8 \
  background.drawing=on \
  position=center_left \
  icon="♫" \
  icon.color=0xffECEFF4 \
  icon.padding_left=8 \
  icon.padding_right=8 \
  label.color=0xffECEFF4 \
  label.padding_left=4 \
  label.padding_right=12 \
  update_freq=5 \
  script="$PLUGIN_DIR/now_playing.sh"

##### Time Block #####
sketchybar --add item clock right \
  --set clock \
  background.color=0xff5E81AC \
  background.corner_radius=0 \
  background.height=22 \
  background.padding_left=8 \
  background.padding_right=0 \
  background.drawing=on \
  icon="" \
  icon.color=0xffECEFF4 \
  icon.padding_left=8 \
  icon.padding_right=8 \
  label.color=0xffECEFF4 \
  label.padding_right=8 \
  update_freq=10 \
  script="$PLUGIN_DIR/clock.sh"

##### Widgets Block (CPU, GPU, Memory, Volume, Battery) #####
sketchybar --add item battery right \
  --set battery \
  background.color=0xff5E81AC \
  background.corner_radius=0 \
  background.height=22 \
  background.padding_left=8 \
  background.padding_right=8 \
  background.drawing=on \
  icon.color=0xffECEFF4 \
  label.color=0xffECEFF4 \
  label.padding_right=8 \
  update_freq=120 \
  script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

sketchybar --add item volume right \
  --set volume \
  background.color=0xff5E81AC \
  background.corner_radius=0 \
  background.height=22 \
  background.padding_left=8 \
  background.padding_right=8 \
  background.drawing=on \
  icon.color=0xffECEFF4 \
  label.color=0xffECEFF4 \
  label.padding_right=8 \
  script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --add item memory right \
  --set memory \
  background.color=0xff5E81AC \
  background.corner_radius=0 \
  background.height=22 \
  background.padding_left=8 \
  background.padding_right=8 \
  background.drawing=on \
  icon= \
  icon.color=0xffECEFF4 \
  icon.padding_left=8 \
  icon.padding_right=8 \
  label.color=0xffECEFF4 \
  label.padding_right=8 \
  update_freq=5 \
  script="$PLUGIN_DIR/memory.sh"

sketchybar --add item gpu right \
  --set gpu \
  background.color=0xff5E81AC \
  background.corner_radius=0 \
  background.height=22 \
  background.padding_left=8 \
  background.padding_right=8 \
  background.drawing=on \
  icon=󰾲 \
  icon.color=0xffECEFF4 \
  label.color=0xffECEFF4 \
  label.padding_right=8 \
  update_freq=5 \
  script="$PLUGIN_DIR/gpu.sh"

sketchybar --add item cpu right \
  --set cpu \
  background.color=0xff5E81AC \
  background.corner_radius=0 \
  background.height=22 \
  background.padding_left=8 \
  background.padding_right=8 \
  background.drawing=on \
  icon= \
  icon.color=0xffECEFF4 \
  icon.padding_left=8 \
  icon.padding_right=8 \
  label.color=0xffECEFF4 \
  label.padding_right=8 \
  update_freq=5 \
  script="$PLUGIN_DIR/cpu.sh"

##### Force all scripts to run the first time #####
sketchybar --update
