#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar position=top height=34 blur_radius=5 color=0xf52e3440 y_offset=0 margin=0 padding_left=0 padding_right=15

sketchybar --bar display=all
sketchybar --add event aerospace_workspace_change

##### Changing Defaults #####
default=(
  icon.font="Hack Nerd Font:Regular:14:0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=0xffe5e9f0
  label.color=0xffd8dee9
  icon.padding_left=8
  icon.padding_right=5
  label.padding_left=0
  label.padding_right=8
  background.padding_left=15
  background.padding_right=0
  # background.color=0xf03b4252
  background.corner_radius=5
  background.height=20
)
sketchybar --default "${default[@]}"

##### Left Side Items #####
sketchybar --add item aerospace left \
  --subscribe aerospace aerospace_workspace_change \
  --set aerospace \
  script="$PLUGIN_DIR/aerospace.sh"

sketchybar --add item input_method left \
  --set input_method \
  icon=󰌌 \
  update_freq=3 \
  script="$PLUGIN_DIR/input_method.sh"

sketchybar --add item front_app left \
  --set front_app \
  icon=">" \
  script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

##### Center Left Item (Now Playing) #####
sketchybar --add item now_playing left \
  --set now_playing \
  icon="󰎆" \
  update_freq=5 \
  script="$PLUGIN_DIR/now_playing.sh"

##### Right Side Items #####
sketchybar --add item audio_device right \
  --set audio_device \
  icon="󰓃" \
  script="$PLUGIN_DIR/audio_device.sh" \
  --subscribe audio_device volume_change

sketchybar --add item volume right \
  --set volume \
  label.padding_right=8 \
  script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --add item battery right \
  --set battery \
  update_freq=120 \
  script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

sketchybar --add item clock right \
  --set clock \
  icon="󰔠" \
  update_freq=10 \
  script="$PLUGIN_DIR/clock.sh"

##### Force all scripts to run the first time #####
sketchybar --update
