#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --remove '/.*/'

##### Bar Appearance #####
sketchybar --bar position=top height=34 blur_radius=5 color=0x00000000 y_offset=0 margin=0 padding_left=0 padding_right=15

sketchybar --bar display=all

##### Changing Defaults #####
default=(
  icon.font="Hack Nerd Font:Regular:14:0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=0xff000000
  label.color=0xff000000
  icon.padding_left=8
  icon.padding_right=5
  label.padding_left=0
  label.padding_right=8
  background.padding_left=15
  background.padding_right=0
  background.corner_radius=5
  background.height=20
)
sketchybar --default "${default[@]}"

##### Left Side Items #####
sketchybar --add item date left \
  --set date \
  update_freq=10 \
  script="$PLUGIN_DIR/date.sh"

sketchybar --add item clock left \
  --set clock \
  background.padding_left=0 \
  update_freq=10 \
  script="$PLUGIN_DIR/clock.sh"

##### Center Items #####
##### Right Side Items #####
sketchybar --add item battery right \
  --set battery \
  update_freq=120 \
  script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

sketchybar --add item volume right \
  --set volume \
  label.padding_right=8 \
  script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --add item memory right \
  --set memory \
  icon="󰍛" \
  update_freq=10 \
  script="$PLUGIN_DIR/memory.sh"

sketchybar --add item github right \
  --set github \
  icon="󰊤" \
  update_freq=60 \
  script="$PLUGIN_DIR/github.sh"

sketchybar --add item slack right \
  --set slack \
  icon="󰒱" \
  update_freq=20 \
  script="$PLUGIN_DIR/slack.sh"

sketchybar --update
