#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar position=top height=34 blur_radius=5 color=0x00000000 y_offset=0 margin=0 padding_left=0 padding_right=15

sketchybar --bar display=all
sketchybar --add event aerospace_workspace_change

##### Changing Defaults #####
default=(
  icon.font="Hack Nerd Font:Regular:14:0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=0xff000000
  label.color=0xff000000
  icon.padding_left=8
  icon.padding_right=5
  label.padding_left=0
  label.padding_right=8
  background.padding_left=15
  background.padding_right=0
  background.corner_radius=5
  background.height=20
)
sketchybar --default "${default[@]}"

##### Left Side Items #####
sketchybar --add item workspace left \
  --subscribe workspace aerospace_workspace_change \
  --set workspace \
  script="$PLUGIN_DIR/workspace.sh"


sketchybar --add item slack left \
  --set slack \
  icon="󰒱" \
  update_freq=20 \
  script="$PLUGIN_DIR/slack.sh" \

sketchybar --add item github left \
  --set github \
  icon="" \
  update_freq=60 \
  script="$PLUGIN_DIR/github.sh" \

sketchybar --add item mail left \
  --set mail \
  icon="󰊫" \
  update_freq=30 \
  script="$PLUGIN_DIR/mail.sh" \


##### Center Items #####
sketchybar --add item date q \
  --set date \
  update_freq=10 \
  script="$PLUGIN_DIR/date.sh"

sketchybar --add item clock e \
  --set clock \
  background.padding_left=0 \
  update_freq=10 \
  script="$PLUGIN_DIR/clock.sh"

##### Right Side Items #####

sketchybar --add item audio_device right \
  --set audio_device \
  icon="" \
  label.max_chars=25 \
  label.scroll_texts=on \
  update_freq=5 \
  script="$PLUGIN_DIR/audio_device.sh" \
  --subscribe audio_device volume_change

sketchybar --add item volume right \
  --set volume \
  label.padding_right=8 \
  script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change

sketchybar --add item battery right \
  --set battery \
  update_freq=120 \
  script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

sketchybar --add item memory right \
  --set memory \
  icon="󰍛" \
  update_freq=10 \
  script="$PLUGIN_DIR/memory.sh"

sketchybar --update
