font_family      Lilex
bold_font        auto
italic_font      auto
bold_italic_font auto
enable_audio_bell no
window_alert_on_bell no
font_size 17
include theme.conf
hide_window_decorations titlebar-only
allow_remote_control yes

# Party trick cursor trail
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.05

background_opacity 0.98
dynamic_background_opacity yes
# Window padding (top right bottom left)
window_padding_width 5 20 0 20
# modify_font cell_height 120% # adjust line height

macos_option_as_alt yes
macos_show_window_title_in none
macos_titlebar_color background

draw_minimal_borders yes
window_border_width 3pt
active_border_color #89b4fa
inactive_border_color #45475a

